test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,26 +44,21 @@ jobs:
       - name: Connect to VM via SSH
         run: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin_@4.233.150.126 << 'EOF'
-          echo 'Connected to VM!'
-          
-          echo "Logging into Docker..."
-          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN" || { echo 'Docker login failed'; exit 1; }
-          echo "Logging into Docker OK"
-          
-          echo "Pulling the latest image..."
-          docker pull "$DOCKER_USERNAME/myapp:latest"
-          
-          # Vérification de l'existence du conteneur avant d'arrêter ou de le supprimer
-          if [ $(docker ps -a -q -f name=myapp | wc -l) -gt 0 ]; then
+            echo 'Connected to VM!'
+            echo "Logging into Docker..."
+            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN" || { echo 'Docker login failed'; exit 1; }
+            echo "Logging into Docker OK"
+            echo "Pulling the latest image..."
+            docker pull "$DOCKER_USERNAME/myapp:latest"
+            if [ $(docker ps -a -q -f name=myapp | wc -l) -gt 0 ]; then
             echo "Stopping and removing existing container..."
             docker stop myapp || true
             docker rm myapp || true
-          else
-            echo "No existing container named 'myapp' found."
-          fi
-
-          echo "Running the new container..."
-          docker run -d --name myapp -p 8088:8088 "$DOCKER_USERNAME/myapp:latest"
+            else
+             echo "No existing container named 'myapp' found."
+            fi
+            echo "Running the new container..."
+            docker run -d --name myapp -p 8088:8088 "$DOCKER_USERNAME/myapp:latest"
 
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
