try

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,17 +43,27 @@ jobs:
 
       - name: Connect to VM via SSH
         run: |
-          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin_@4.233.150.126 "echo 'Connected to VM!'"
-            echo "Logging into Docker..."
-            docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
-            echo "Logging into Docker OK"
-            docker pull $DOCKER_USERNAME/myapp:latest
-            echo "PULL"
+           ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin_@4.233.150.126 << 'EOF'
+          echo 'Connected to VM!'
+          
+          echo "Logging into Docker..."
+          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_TOKEN" || { echo 'Docker login failed'; exit 1; }
+          echo "Logging into Docker OK"
+          
+          echo "Pulling the latest image..."
+          docker pull "$DOCKER_USERNAME/myapp:latest"
+          
+          # Vérification de l'existence du conteneur avant d'arrêter ou de le supprimer
+          if [ $(docker ps -a -q -f name=myapp | wc -l) -gt 0 ]; then
+            echo "Stopping and removing existing container..."
             docker stop myapp || true
-            echo "STOP"
             docker rm myapp || true
-            echo "RM"
-            docker run -d --name myapp -p 80:80 $DOCKER_USERNAME/myapp:latest
+          else
+            echo "No existing container named 'myapp' found."
+          fi
+
+          echo "Running the new container..."
+          docker run -d --name myapp -p 8088:8088 "$DOCKER_USERNAME/myapp:latest"
 
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
@@ -74,3 +84,16 @@ jobs:
     #     env:
     #       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
     #       DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
+
+
+    # ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin_@4.233.150.126 "echo 'Connected to VM!'"
+    #         echo "Logging into Docker..."
+    #         docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
+    #         echo "Logging into Docker OK"
+    #         docker pull $DOCKER_USERNAME/myapp:latest
+    #         echo "PULL"
+    #         docker stop myapp || true
+    #         echo "STOP"
+    #         docker rm myapp || true
+    #         echo "RM"
+    #         docker run -d --name myapp -p 80:80 $DOCKER_USERNAME/myapp:latest
