test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -43,17 +43,32 @@ jobs:
 
       - name: Connect to VM via SSH
         run: |
-            export DOCKER_USERNAME=$DOCKER_USERNAME
-            export DOCKER_TOKEN=$DOCKER_TOKEN
-            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin_@4.233.150.126 "echo 'Connected to VM!'"
-                echo "Logging into Docker..."
-                docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN
-                echo "Logging into Docker OK"
-                docker pull $DOCKER_USERNAME/myapp:latest
-                echo "PULL"
-                echo "RM"
-                docker run -d --name staging-container -p 8088:8088 $DOCKER_USERNAME/myapp:latest
-                echo "run"
+           ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin_@4.233.150.126 << 'EOF'
+            echo 'Connected to VM!'
+            
+            # Connexion à Docker
+            echo "Logging into Docker..."
+            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_TOKEN}" || { echo 'Docker login failed'; exit 1; }
+            echo "Logging into Docker OK"
+
+            # Tirer l'image Docker
+            echo "Pulling the latest image..."
+            docker pull "${DOCKER_USERNAME}/myapp:latest" || { echo 'Docker pull failed'; exit 1; }
+
+            # Arrêter et supprimer le conteneur s'il existe
+            if [ $(docker ps -a -q -f name=myapp | wc -l) -gt 0 ]; then
+              echo "Stopping and removing existing container..."
+              docker stop myapp || true
+              docker rm myapp || true
+            else
+              echo "No existing container named 'myapp' found."
+            fi
+
+            # Exécuter le nouveau conteneur
+            echo "Running the new container..."
+            docker run -d --name myapp -p 8088:8088 "${DOCKER_USERNAME}/myapp:latest" || { echo 'Failed to run container'; exit 1; }
+            echo "Container is running"
+          EOF
         env:
           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
           DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
